spring:
  cloud:
    gateway:
      routes:
        - id: violation-disposition-route
          uri: lb://violation-disposition
          predicates:
            - Path=/api/violation-disposition/**
          filters:
            - RewritePath=/api/violation-disposition/?(?<segment>.*), /$\{segment}
        - id: detection-view-route
          uri: lb://detection-review
          predicates:
            - Path=/api/detection-review/**
          filters:
            - RewritePath=/api/detection-review/?(?<segment>.*), /$\{segment}