<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.czming</groupId>
        <artifactId>services</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>detection-review</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <javacv.version>1.5.10</javacv.version>

        <javacv.platform.macosx-arm64>macosx-arm64</javacv.platform.macosx-arm64>
        <javacv.platform.linux-x86_64>linux-x86_64</javacv.platform.linux-x86_64>
        <javacv.platform.linux-arm64>linux-arm64</javacv.platform.linux-arm64>
        <javacv.platform.windows-x86_64>windows-x86_64</javacv.platform.windows-x86_64>

        <djl.platform.windows-x86_64>win-x86_64</djl.platform.windows-x86_64>
        <djl.platform.linux-x86_64>linux-x86_64</djl.platform.linux-x86_64>
        <djl.platform.linux-aarch64>linux-aarch64</djl.platform.linux-aarch64>
        <djl.platform.osx-aarch64>osx-aarch64</djl.platform.osx-aarch64>

    </properties>

    <dependencies>
        <dependency>
            <groupId>cn.smartjavaai</groupId>
            <artifactId>vision</artifactId>
            <version>1.1.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.microsoft.onnxruntime</groupId>
                    <artifactId>onnxruntime</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>cn.smartjavaai</groupId>
            <artifactId>ocr</artifactId>
            <version>1.1.1</version>
            <exclusions>
                <exclusion>
                    <groupId>com.microsoft.onnxruntime</groupId>
                    <artifactId>onnxruntime</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime_gpu</artifactId>
            <version>1.20.0</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-jni</artifactId>
            <version>2.7.1-0.34.0</version>
            <scope>runtime</scope>
        </dependency>

    </dependencies>


    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>

        <resources>
            <resource>
                <directory>
                    src/main/resources
                </directory>
                <excludes>
                    <exclude>model/**</exclude>
                </excludes>
            </resource>
        </resources>
    </build>

</project>